# Generated by Django 5.2.7 on 2025-10-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='["", "", "", "", "", "", "", "", ""]', max_length=255)),
                ('current_player', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
